affine_trainable: false
auto_save: true
base_fun_name: zero
ckpt_path: ./model
device: cpu
grid: 2
grid_eps: 0
grid_range:
- 0
- 1
k: 1
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 2
symbolic.funs_name.0:
- - '0'
- - '0'
symbolic.funs_name.1:
- - '0'
  - '0'
symbolic_enabled: false
width:
- - 1
  - 0
- - 2
  - 0
- - 1
  - 0
